#!/usr/bin/env python3
"""
新專案基礎設施設定腳本

這個腳本示範如何在新專案中使用 Infrastructure MCP Server 來設定基礎設施。

使用方式:
    1. 複製此檔案到你的專案目錄
    2. 設定環境變數:
       export CF_ACCESS_CLIENT_ID="your_client_id"
       export CF_ACCESS_CLIENT_SECRET="your_client_secret"
    3. 執行: python new_project_setup.py

或者使用命令列參數:
    python new_project_setup.py --project my-app --service web --hostname myapp.nowhere.tw --port 5000
"""

import asyncio
import argparse
import os
import sys
from pathlib import Path

# 如果 infra_client 不在同一目錄，調整路徑
sys.path.insert(0, str(Path(__file__).parent))
from infra_client import InfrastructureMCPClient, setup_project_infrastructure


async def setup_infrastructure_interactive():
    """互動式設定基礎設施"""
    print("🚀 Infrastructure MCP - 新專案設定")
    print("=" * 50)

    # 收集資訊
    project = input("專案名稱 (例如: my-blog): ").strip()
    service = input("服務名稱 (例如: web, api, frontend): ").strip()
    hostname = input("公開 hostname (例如: myapp.nowhere.tw): ").strip()
    port_input = input("偏好的 port (留空自動分配): ").strip()
    preferred_port = int(port_input) if port_input else None

    deploy = input("是否部署到 VPS? (y/N): ").strip().lower()
    deploy_server = None
    if deploy == 'y':
        deploy_server = input("伺服器名稱 (例如: asablue): ").strip()

    print("\n正在設定基礎設施...")

    try:
        result = await setup_project_infrastructure(
            project_name=project,
            service_name=service,
            hostname=hostname,
            preferred_port=preferred_port,
            deploy_server=deploy_server
        )

        print("\n✅ 基礎設施設定完成！")
        print("=" * 50)
        print(f"專案: {result['project']}")
        print(f"服務: {result['service']}")
        print(f"Port: {result['port']}")
        print(f"Tunnel: {result['tunnel']}")
        print(f"公開 URL: https://{result['hostname']}")

        if deploy_server:
            print(f"部署至: {result['deployed_to']}")

        print("\n📝 下一步:")
        print(f"1. 啟動你的應用在 port {result['port']}")
        print(f"2. 訪問 https://{result['hostname']} 查看結果")

        # 產生配置檔
        generate_config = input("\n是否產生配置檔? (Y/n): ").strip().lower()
        if generate_config != 'n':
            config_content = f"""# Infrastructure Configuration
# Generated by Infrastructure MCP Server

PROJECT_NAME={result['project']}
SERVICE_NAME={result['service']}
PORT={result['port']}
TUNNEL_NAME={result['tunnel']}
PUBLIC_URL=https://{result['hostname']}
"""
            if deploy_server:
                config_content += f"DEPLOYED_TO={result['deployed_to']}\n"

            with open(".infra.env", "w") as f:
                f.write(config_content)

            print("✅ 配置已寫入 .infra.env")
            print("   記得將 .infra.env 加入 .gitignore")

    except Exception as e:
        print(f"\n❌ 設定失敗: {e}", file=sys.stderr)
        return 1

    return 0


async def setup_infrastructure_cli(args):
    """使用命令列參數設定基礎設施"""
    print(f"🚀 設定基礎設施: {args.project}/{args.service}")

    try:
        result = await setup_project_infrastructure(
            project_name=args.project,
            service_name=args.service,
            hostname=args.hostname,
            preferred_port=args.port,
            deploy_server=args.server
        )

        print("\n✅ 基礎設施設定完成！")
        print(f"   Port: {result['port']}")
        print(f"   URL: https://{result['hostname']}")

        if args.server:
            print(f"   Deployed to: {result['deployed_to']}")

        return 0

    except Exception as e:
        print(f"❌ 設定失敗: {e}", file=sys.stderr)
        return 1


async def list_all_resources():
    """列出所有已分配的資源"""
    print("📋 列出所有已分配的資源...")

    client = InfrastructureMCPClient(
        client_id=os.getenv("CF_ACCESS_CLIENT_ID"),
        client_secret=os.getenv("CF_ACCESS_CLIENT_SECRET")
    )

    try:
        result = await client.list_resources()
        content = result["result"]["content"][0]["text"]
        print("\n" + content)
        return 0
    except Exception as e:
        print(f"❌ 查詢失敗: {e}", file=sys.stderr)
        return 1


async def health_check():
    """檢查 MCP Server 健康狀態"""
    print("🏥 檢查 MCP Server 健康狀態...")

    client = InfrastructureMCPClient(
        client_id=os.getenv("CF_ACCESS_CLIENT_ID"),
        client_secret=os.getenv("CF_ACCESS_CLIENT_SECRET")
    )

    is_healthy = await client.health_check()

    if is_healthy:
        print("✅ MCP Server 運行正常")
        return 0
    else:
        print("❌ MCP Server 無法連線", file=sys.stderr)
        return 1


def main():
    """主程式"""
    parser = argparse.ArgumentParser(
        description="Infrastructure MCP - 新專案設定工具"
    )

    subparsers = parser.add_subparsers(dest="command", help="可用指令")

    # setup 指令
    setup_parser = subparsers.add_parser("setup", help="設定新專案基礎設施")
    setup_parser.add_argument("--project", help="專案名稱")
    setup_parser.add_argument("--service", help="服務名稱")
    setup_parser.add_argument("--hostname", help="公開 hostname")
    setup_parser.add_argument("--port", type=int, help="偏好的 port")
    setup_parser.add_argument("--server", help="部署伺服器名稱")

    # list 指令
    subparsers.add_parser("list", help="列出所有已分配的資源")

    # health 指令
    subparsers.add_parser("health", help="檢查 MCP Server 健康狀態")

    args = parser.parse_args()

    # 檢查環境變數
    if not os.getenv("CF_ACCESS_CLIENT_ID") or not os.getenv("CF_ACCESS_CLIENT_SECRET"):
        print("⚠️  警告: 未設定 Cloudflare Access 認證資訊", file=sys.stderr)
        print("請設定以下環境變數:", file=sys.stderr)
        print("  export CF_ACCESS_CLIENT_ID='your_client_id'", file=sys.stderr)
        print("  export CF_ACCESS_CLIENT_SECRET='your_client_secret'", file=sys.stderr)
        print("\n如果只是測試，確保 MCP Server 的 Access 保護已暫時移除。")
        print()

    # 執行對應指令
    if args.command == "setup":
        if args.project and args.service and args.hostname:
            # CLI 模式
            exit_code = asyncio.run(setup_infrastructure_cli(args))
        else:
            # 互動模式
            exit_code = asyncio.run(setup_infrastructure_interactive())
    elif args.command == "list":
        exit_code = asyncio.run(list_all_resources())
    elif args.command == "health":
        exit_code = asyncio.run(health_check())
    else:
        # 沒有指定指令，使用互動模式
        exit_code = asyncio.run(setup_infrastructure_interactive())

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
