#!/usr/bin/env python3
"""
New Project Infrastructure Setup Script

This script demonstrates how to use the Infrastructure MCP Server to set up
infrastructure for a new project.

Usage:
    1. Copy this file to your project directory
    2. Set environment variables:
       export CF_ACCESS_CLIENT_ID="your_client_id"
       export CF_ACCESS_CLIENT_SECRET="your_client_secret"
    3. Run: python new_project_setup.py

Or use command-line arguments:
    python new_project_setup.py --project my-app --service web --hostname myapp.your-domain.com --port 5000
"""

import asyncio
import argparse
import os
import sys
from pathlib import Path

# Adjust path if infra_client is not in the same directory
sys.path.insert(0, str(Path(__file__).parent))
from infra_client import InfrastructureMCPClient, setup_project_infrastructure


async def setup_infrastructure_interactive():
    """Set up infrastructure interactively via prompts."""
    print("🚀 Infrastructure MCP - New Project Setup")
    print("=" * 50)

    # Collect information
    project = input("Project name (e.g. my-blog): ").strip()
    service = input("Service name (e.g. web, api, frontend): ").strip()
    hostname = input("Public hostname (e.g. myapp.your-domain.com): ").strip()
    port_input = input("Preferred port (leave blank for auto-assign): ").strip()
    preferred_port = int(port_input) if port_input else None

    deploy = input("Deploy to VPS? (y/N): ").strip().lower()
    deploy_server = None
    if deploy == 'y':
        deploy_server = input("Server name (e.g. prod): ").strip()

    print("\nSetting up infrastructure...")

    try:
        result = await setup_project_infrastructure(
            project_name=project,
            service_name=service,
            hostname=hostname,
            preferred_port=preferred_port,
            deploy_server=deploy_server
        )

        print("\n✅ Infrastructure setup complete!")
        print("=" * 50)
        print(f"Project: {result['project']}")
        print(f"Service: {result['service']}")
        print(f"Port: {result['port']}")
        print(f"Tunnel: {result['tunnel']}")
        print(f"Public URL: https://{result['hostname']}")

        if deploy_server:
            print(f"Deployed to: {result['deployed_to']}")

        print("\n📝 Next steps:")
        print(f"1. Start your application on port {result['port']}")
        print(f"2. Visit https://{result['hostname']} to verify")

        # Optionally generate a config file
        generate_config = input("\nGenerate config file? (Y/n): ").strip().lower()
        if generate_config != 'n':
            config_content = f"""# Infrastructure Configuration
# Generated by Infrastructure MCP Server

PROJECT_NAME={result['project']}
SERVICE_NAME={result['service']}
PORT={result['port']}
TUNNEL_NAME={result['tunnel']}
PUBLIC_URL=https://{result['hostname']}
"""
            if deploy_server:
                config_content += f"DEPLOYED_TO={result['deployed_to']}\n"

            with open(".infra.env", "w") as f:
                f.write(config_content)

            print("✅ Config written to .infra.env")
            print("   Remember to add .infra.env to your .gitignore")

    except Exception as e:
        print(f"\n❌ Setup failed: {e}", file=sys.stderr)
        return 1

    return 0


async def setup_infrastructure_cli(args):
    """Set up infrastructure using command-line arguments."""
    print(f"🚀 Setting up infrastructure: {args.project}/{args.service}")

    try:
        result = await setup_project_infrastructure(
            project_name=args.project,
            service_name=args.service,
            hostname=args.hostname,
            preferred_port=args.port,
            deploy_server=args.server
        )

        print("\n✅ Infrastructure setup complete!")
        print(f"   Port: {result['port']}")
        print(f"   URL: https://{result['hostname']}")

        if args.server:
            print(f"   Deployed to: {result['deployed_to']}")

        return 0

    except Exception as e:
        print(f"❌ Setup failed: {e}", file=sys.stderr)
        return 1


async def list_all_resources():
    """List all allocated resources."""
    print("📋 Listing all allocated resources...")

    client = InfrastructureMCPClient(
        client_id=os.getenv("CF_ACCESS_CLIENT_ID"),
        client_secret=os.getenv("CF_ACCESS_CLIENT_SECRET")
    )

    try:
        result = await client.list_resources()
        content = result["result"]["content"][0]["text"]
        print("\n" + content)
        return 0
    except Exception as e:
        print(f"❌ Query failed: {e}", file=sys.stderr)
        return 1


async def health_check():
    """Check MCP Server health status."""
    print("🏥 Checking MCP Server health...")

    client = InfrastructureMCPClient(
        client_id=os.getenv("CF_ACCESS_CLIENT_ID"),
        client_secret=os.getenv("CF_ACCESS_CLIENT_SECRET")
    )

    is_healthy = await client.health_check()

    if is_healthy:
        print("✅ MCP Server is running normally")
        return 0
    else:
        print("❌ MCP Server is unreachable", file=sys.stderr)
        return 1


def main():
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Infrastructure MCP - New project setup tool"
    )

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # setup command
    setup_parser = subparsers.add_parser("setup", help="Set up infrastructure for a new project")
    setup_parser.add_argument("--project", help="Project name")
    setup_parser.add_argument("--service", help="Service name")
    setup_parser.add_argument("--hostname", help="Public hostname")
    setup_parser.add_argument("--port", type=int, help="Preferred port number")
    setup_parser.add_argument("--server", help="Deployment server name")

    # list command
    subparsers.add_parser("list", help="List all allocated resources")

    # health command
    subparsers.add_parser("health", help="Check MCP Server health status")

    args = parser.parse_args()

    # Check environment variables
    if not os.getenv("CF_ACCESS_CLIENT_ID") or not os.getenv("CF_ACCESS_CLIENT_SECRET"):
        print("⚠️  Warning: Cloudflare Access credentials not set", file=sys.stderr)
        print("Please set the following environment variables:", file=sys.stderr)
        print("  export CF_ACCESS_CLIENT_ID='your_client_id'", file=sys.stderr)
        print("  export CF_ACCESS_CLIENT_SECRET='your_client_secret'", file=sys.stderr)
        print("\nFor testing only, ensure Access protection has been temporarily removed from the MCP Server.")
        print()

    # Dispatch to the appropriate command handler
    if args.command == "setup":
        if args.project and args.service and args.hostname:
            # CLI mode
            exit_code = asyncio.run(setup_infrastructure_cli(args))
        else:
            # Interactive mode
            exit_code = asyncio.run(setup_infrastructure_interactive())
    elif args.command == "list":
        exit_code = asyncio.run(list_all_resources())
    elif args.command == "health":
        exit_code = asyncio.run(health_check())
    else:
        # No command specified — fall back to interactive mode
        exit_code = asyncio.run(setup_infrastructure_interactive())

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
